package repository

import "ebike-battery-backend/internal/ds"

func motorModeCollection() []ds.MotorMode {
	return []ds.MotorMode{
		{
			ID:                 1,
			ModeName:           "Eco",
			ShortDescription:   "Слабая поддержка с максимальной экономичностью для наибольшего запаса хода. Мотор добавляет к усилию педалей не более 60 %, поэтому аккумулятор PowerTube 800 расходуется медленнее всего. Базовый режим для равнинных маршрутов и длинных дистанций.",
			Status:             ds.StatusPublished,
			ImageKey:           "eco_mode.jpg",
			VideoKey:           "eco_mode.mp4",
			SupportPercent:     60,
			ConsumptionWhPerKm: 5.2,
			MaxTorqueNm:        120,
			DriveUnit:          "Performance Line CX",
			SupportCharacter:   "постоянная",
			LikedByRiderIDs:    []int{1, 2, 3, 5, 8, 13},
		},
		{
			ID:                 2,
			ModeName:           "Eco+",
			ShortDescription:   "Мотор включается только под повышенной нагрузкой, например на подъемах. На ровном участке поддержка отключена полностью, поэтому расход аккумулятора самый низкий во всей линейке режимов.",
			Status:             ds.StatusPublished,
			ImageKey:           "eco_plus_mode.jpg",
			VideoKey:           "eco_plus_mode.mp4",
			SupportPercent:     60,
			ConsumptionWhPerKm: 4.6,
			MaxTorqueNm:        60,
			DriveUnit:          "Performance Line SX",
			SupportCharacter:   "автоматическая",
			LikedByRiderIDs:    []int{2, 7},
		},
		{
			ID:                 3,
			ModeName:           "Tour",
			ShortDescription:   "Равномерная поддержка для поездок с большим запасом хода. Мотор добавляет до 140 % усилия педалей и держит его постоянным, что дает предсказуемый расход аккумулятора на протяженном маршруте.",
			Status:             ds.StatusPublished,
			ImageKey:           "tour_mode.jpg",
			VideoKey:           "tour_mode.mp4",
			SupportPercent:     140,
			ConsumptionWhPerKm: 7.8,
			MaxTorqueNm:        75,
			DriveUnit:          "Performance Line",
			SupportCharacter:   "спортивная",
			LikedByRiderIDs:    []int{1, 4, 6, 9},
		},
		{
			ID:                 4,
			ModeName:           "Tour+",
			ShortDescription:   "Плавно нарастающая поддержка до 340 % для экономичной езды и естественных ощущений на спортивных маршрутах. Мотор подстраивает мощность под каденс, поэтому расход ниже, чем у Turbo при том же максимуме поддержки.",
			Status:             ds.StatusPublished,
			ImageKey:           "tour_plus_mode.jpg",
			VideoKey:           "tour_plus_mode.mp4",
			SupportPercent:     340,
			ConsumptionWhPerKm: 10.4,
			MaxTorqueNm:        120,
			DriveUnit:          "Performance Line CX",
			SupportCharacter:   "спортивная",
			LikedByRiderIDs:    []int{3, 5, 11, 12, 14},
		},
		{
			ID:                 5,
			ModeName:           "Sport",
			ShortDescription:   "Мощная поддержка до 240 % для универсального применения: и для спортивной езды, и для быстрых поездок по городу. Средний расход аккумулятора при заметно более высокой динамике разгона.",
			Status:             ds.StatusPublished,
			ImageKey:           "sport_mode.jpg",
			VideoKey:           "sport_mode.mp4",
			SupportPercent:     240,
			ConsumptionWhPerKm: 11.2,
			MaxTorqueNm:        60,
			DriveUnit:          "Active Line Plus",
			SupportCharacter:   "постоянная",
			LikedByRiderIDs:    []int{2, 6, 10},
		},
		{
			ID:                 6,
			ModeName:           "eMTB",
			ShortDescription:   "Динамическая поддержка до 340 % для естественного поведения байка и оптимального контроля на горных маршрутах. Мотор реагирует на усилие педалей прогрессивно, расход аккумулятора высокий.",
			Status:             ds.StatusPublished,
			ImageKey:           "emtb_mode.jpg",
			VideoKey:           "emtb_mode.mp4",
			SupportPercent:     340,
			ConsumptionWhPerKm: 13.5,
			MaxTorqueNm:        120,
			DriveUnit:          "Performance Line CX",
			SupportCharacter:   "спортивная",
			LikedByRiderIDs:    []int{4, 8, 15, 16},
		},
		{
			ID:                 7,
			ModeName:           "eMTB+",
			ShortDescription:   "Динамическая поддержка до предела: точная управляемость режима eMTB вместе с функцией Extended Boost. Максимум 400 % поддержки, поэтому заряд аккумулятора расходуется очень быстро.",
			Status:             ds.StatusPublished,
			ImageKey:           "emtb_plus_mode.jpg",
			VideoKey:           "emtb_plus_mode.mp4",
			SupportPercent:     400,
			ConsumptionWhPerKm: 15.8,
			MaxTorqueNm:        120,
			DriveUnit:          "Performance Line CX",
			SupportCharacter:   "спортивная",
			LikedByRiderIDs:    []int{7, 9},
		},
		{
			ID:                 8,
			ModeName:           "Turbo",
			ShortDescription:   "Прямая максимальная поддержка вплоть до самого высокого каденса, рассчитанная на крутые подъемы. Мотор постоянно отдает до 340 % усилия педалей, что дает наибольший расход среди базовых режимов.",
			Status:             ds.StatusPublished,
			ImageKey:           "turbo_mode.jpg",
			VideoKey:           "turbo_mode.mp4",
			SupportPercent:     340,
			ConsumptionWhPerKm: 16.4,
			MaxTorqueNm:        120,
			DriveUnit:          "Performance Line CX",
			SupportCharacter:   "постоянная",
			LikedByRiderIDs:    []int{1, 3, 5, 7, 9, 11, 13, 17},
		},
		{
			ID:                 9,
			ModeName:           "Race",
			ShortDescription:   "Бескомпромиссная динамика и максимальная поддержка от старта до финиша для самых сложных гонок на электровелосипедах. Поддержка до 400 % удерживается постоянно, запас хода минимальный.",
			Status:             ds.StatusPublished,
			ImageKey:           "race_mode.jpg",
			VideoKey:           "race_mode.mp4",
			SupportPercent:     400,
			ConsumptionWhPerKm: 18.6,
			MaxTorqueNm:        120,
			DriveUnit:          "Performance Line CX-R",
			SupportCharacter:   "постоянная",
			LikedByRiderIDs:    []int{12, 18},
		},
		{
			ID:                 10,
			ModeName:           "Sprint",
			ShortDescription:   "Динамическая поддержка, растущая вместе с каденсом, для ускорений и коротких крутых подъемов. Максимум 280 % при среднем расходе аккумулятора, режим рассчитан на легкий привод Performance Line SX.",
			Status:             ds.StatusPublished,
			ImageKey:           "sprint_mode.jpg",
			VideoKey:           "sprint_mode.mp4",
			SupportPercent:     280,
			ConsumptionWhPerKm: 12.1,
			MaxTorqueNm:        60,
			DriveUnit:          "Performance Line SX",
			SupportCharacter:   "спортивная",
			LikedByRiderIDs:    []int{6, 10, 14},
		},
		{
			ID:                 11,
			ModeName:           "Cargo",
			ShortDescription:   "Максимальная поддержка до 400 % от усилия велосипедиста и оптимальное поведение при старте даже с полной загрузкой. Режим рассчитан на грузовой привод Cargo Line с моментом 120 Нм.",
			Status:             ds.StatusPublished,
			ImageKey:           "cargo_mode.jpg",
			VideoKey:           "cargo_mode.mp4",
			SupportPercent:     400,
			ConsumptionWhPerKm: 19.5,
			MaxTorqueNm:        120,
			DriveUnit:          "Cargo Line",
			SupportCharacter:   "автоматическая",
			LikedByRiderIDs:    []int{8, 15},
		},
		{
			ID:                 12,
			ModeName:           "Auto",
			ShortDescription:   "Автоматическая подстройка поддержки при падении скорости из-за подъема или встречного ветра. Мотор сам выбирает уровень до 340 %, велосипедисту не нужно переключать режимы вручную.",
			Status:             ds.StatusPublished,
			ImageKey:           "auto_mode.jpg",
			VideoKey:           "auto_mode.mp4",
			SupportPercent:     340,
			ConsumptionWhPerKm: 12.8,
			MaxTorqueNm:        40,
			DriveUnit:          "Active Line",
			SupportCharacter:   "автоматическая",
			LikedByRiderIDs:    []int{2, 4, 16, 19},
		},
		{
			ID:                 13,
			ModeName:           "Limit",
			ShortDescription:   "Мотор S-Pedelec помогает только до 25 км/ч вместо 45 км/ч: экономичнее и удобнее для поездок в группе.",
			Status:             ds.StatusDraft,
			ImageKey:           "limit_mode.jpg",
			VideoKey:           "limit_mode.mp4",
			SupportPercent:     340,
			ConsumptionWhPerKm: 13.0,
			MaxTorqueNm:        85,
			DriveUnit:          "Performance Line Speed",
			SupportCharacter:   "автоматическая",
			LikedByRiderIDs:    []int{},
		},
		{
			ID:                 14,
			ModeName:           "Off",
			ShortDescription:   "Поддержка отключена полностью, доступны только функции дисплея. Режим снят с публикации и не должен отображаться велосипедисту.",
			Status:             ds.StatusDeleted,
			ImageKey:           "off_mode.jpg",
			VideoKey:           "off_mode.mp4",
			SupportPercent:     0,
			ConsumptionWhPerKm: 0,
			MaxTorqueNm:        0,
			DriveUnit:          "Performance Line",
			SupportCharacter:   "отсутствует",
			LikedByRiderIDs:    []int{20},
		},
	}
}
